name: test

on:
  repository_dispatch:

  workflow_dispatch:
    inputs:
      runenv:
        description: "Value"
        required: false
        default: ""

env:
  RUN_ENV: ${{ github.event.inputs.runenv }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set RUN_ENV for Repo Dispatch
        if: github.event_name == 'repository_dispatch' && ${{ github.event.client_payload.env }} != ''
        run: |
          case ${{ github.event.client_payload.env }} in
          development)
            export RUN_ENV=dev,devtestconstants
            ;;
          *)
            echo "We only need to set this for Dev Env"
            ;;
          esac

          echo $RUN_ENV
