name: test

on:
  repository_dispatch:

  workflow_dispatch:
    inputs:
      runenv:
        description: "Value"
        required: false
        default: ""

env:
  RUN_ENV: ${{ github.event.inputs.runenv }}
  RUN_WORKFLOW: "true"

jobs:
  set_runenv:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Set RUN_ENV for Repo Dispatch
        run: |
          # export ENV="${{ github.event.client_payload.env }}"
          export ENV="${{ github.event.inputs.runenv }}"
          case $ENV in
          development)
            export RUN_ENV=dev,devtestconstants
            echo "RUN_ENV is $RUN_ENV"
            ;;
          load)

            ;;
          *)
            echo "We only need to set this for Dev Env"
            export RUN_WORKFLOW="false"
            ;;
          esac

          echo $RUN_ENV

  test:
    runs-on: ubuntu-latest
    if: ${{ $RUN_WORKFLOW == "true" }}
    steps:
      - run: echo "Voila!"
