name: test

on:
  repository_dispatch:

  workflow_dispatch:
    inputs:
      runenv:
        description: "Value"
        required: false
        default: ""

env:
  RUN_ENV: ${{ github.event.inputs.runenv }}

jobs:
  set_runenv:
    runs-on: ubuntu-latest
    outputs:
      RUN_WORKFLOW: ${{ steps.dispatch.outputs.RUN_WORKFLOW }}
    steps:
      - name: Set RUN_ENV for Repo Dispatch
        id: dispatch
        run: |
          case ${{ github.event.inputs.runenv }} in
          development)
            echo "::set-output name=RUN_WORKFLOW::'true'"
            ;;
          load)
            echo "::set-output name=RUN_WORKFLOW::true"
            ;;
          *)
            echo "::set-output name=RUN_WORKFLOW::false"
            ;;
          esac
  test:
    runs-on: ubuntu-latest
    needs: [set_runenv]
    if: startsWith(github.ref, 'refs/heads/master') && contains(needs.set_runenv.outputs.RUN_WORKFLOW, 'true')
    steps:
      - run: echo "Voila!"
