name: test

on:
  repository_dispatch:

  workflow_dispatch:
    inputs:
      runenv:
        description: "Value"
        required: false
        default: ""

env:
  RUN_ENV: ${{ github.event.inputs.runenv }}

jobs:
  set_runenv:
    runs-on: ubuntu-latest
    outputs:
      RUN_WORKFLOW: ${{ env.RUN_WORKFLOW }}
    steps:
      - name: Set RUN_ENV for Repo Dispatch
        run: |
          # export ENV="${{ github.event.client_payload.env }}"
          export ENV="${{ github.event.inputs.runenv }}"
          case $ENV in
          development)
            export RUN_ENV=dev,devtestconstants
            echo "RUN_ENV is $RUN_ENV"
            ;;
          load)

            ;;
          *)
            echo "We only need to set this for Dev Env"
            echo RUN_WORKFLOW="false" >> $GITHUB_ENV
            ;;
          esac
  test:
    runs-on: ubuntu-latest
    needs: [set_runenv]
    if: contains(needs.isRelease.outputs.RUN_WORKFLOW, 'true')
    steps:
      - run: echo "Voila!"
